import { Sidebar } from "@/components/Sidebar";
import ClientToast from "@/components/client/ClientToast";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme-toggle";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthAlert } from "@/components/client/AuthAlert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					<div className="h-screen">
						<div className="grid grid-cols-4 h-full">
							<Sidebar />
							<div
								className="col-span-3 border-x-[1px] 
								border-neutral-200 
              dark:border-neutral-800 lg:col-span-2"
							>
								{children}
							</div>
						</div>
					</div>
					<ClientToast />
					<ModeToggle />
				</ThemeProvider>
			</body>
		</html>
	);
}
